Add a picker provider
terminal42/contao-DC_Multilingual pull request #74
Opened 2022-05-17 08:04 UTC by dmolineus

This pull requests adds the picker support for multilingual data containers.

2022-05-17 08:47 UTC, aschempp commented
Can you explain what the picker class offers that the universal picker does not?

2022-05-17 08:51 UTC, dmolineus commented
> I guess we need a custom picker because just to support our driver class, right?

Yes, the generic picker is limited to `DC_Table`, see https://github.com/contao/contao/blob/50502c09eec66d75b1c1ae280ceec90a0ab4ca62/core-bundle/src/Picker/TablePickerProvider.php#L26

2022-05-17 09:04 UTC, aschempp commented
just let me know when you tested this and if I should release 4.3 right-away or you maybe have some more stuff coming up 🙃

2022-06-24 13:47 UTC, benfolds commented
Is there a schedule for this pull request? Can i buy some coffee?

2022-07-04 07:43 UTC, dmolineus commented
@aschempp I had to adjust the implementation to support both driver names `Multilingual` and the FCQN `Driver::class` in [7e8f3d1](https://github.com/terminal42/contao-DC_Multilingual/pull/74/commits/7e8f3d1e3c96be5c1b2f2d7453435a0ba84a63e6). I did not stumple upon any other issue so it's ready to merge from my point of view.

2022-07-05 14:02 UTC, aschempp requested changes

2022-07-14 12:07 UTC, aschempp commented on src/Driver.php
> +        if ('' !== $intId && $intId !== null)
changed in d5739f33e29c549f04b5af31e761022cedf411de to what the Contao Core does
https://github.com/contao/contao/blob/5.x/core-bundle/src/Resources/contao/drivers/DC_Table.php#L1783

2022-07-14 12:14 UTC, aschempp commented on src/Picker/MultilingualPickerProvider.php
> +        $driverClass = DataContainer::getDriverForTable($table);
I have simplified the fix in 166879a1b3686e5581cff89fd92eafc6525f985b

2022-07-14 12:15 UTC, aschempp approved these changes

2022-07-14 12:15 UTC, merged

2022-07-14 12:15 UTC, aschempp commented
Thank you @dmolineus